### ============================================================================
# Flux quality control =========================================================
### ============================================================================

# Purpose: 

# References:

# Vitale, D., Fratini, G., Bilancia, M., Nicolini, G., Sabbatini, S., & Papale, 
# D. (2020). A robust data cleaning procedure for eddy covariance flux 
# measurements. Biogeosciences, 17(6), 1367–1391. 
# https://doi.org/10.5194/bg-17-1367-2020


# Input(s):

# Output(s):

start_time <- Sys.time()

# Load the required packages
library(lubridate, warn.conflicts = FALSE)
library(tidyverse)

# Load reference files
source("~/Desktop/DATA/Flux/tools/reference/site_metadata.R")
source("~/Desktop/DATA/Flux/tools/reference/essential_vars.R")

# Load functions
source("~/Desktop/DATA/Flux/tools/engine/functions/clean.R")
source("~/Desktop/DATA/Flux/tools/engine/functions/dates_and_times.R")
source("~/Desktop/DATA/Flux/tools/engine/functions/flag.R")
source("~/Desktop/DATA/Flux/tools/engine/functions/latest_version.R")
source("~/Desktop/DATA/Flux/tools/engine/functions/utilities.R")


### Helper functions ===========================================================



### Initialize script settings & documentation =================================

# Load metadata file
md <- purrr::pluck(site_metadata, settings$site)

# Set the desired working directory in RStudio interface
# - assumes that the subdirectory structure is already present
wd <- file.path("~/Desktop", "DATA", "Flux", settings$site, settings$year)
path_in <- file.path(wd, "processing", "04_biomet_gapfill", "data")
ep_path_in <- file.path(wd, "processing", "01_combine_eddypro")
fp_path_in <- file.path(wd, "processing", "05_footprint", "stats")

# Input file - biomet output with QC flags
data_input <- latest_version(path_in, "biomet_gf")

# EddyPro outputs (for RFlux)
ep_path <- latest_version(file.path(ep_path_in, "full_output"))
qc_path <- latest_version(file.path(ep_path_in, "qc_details"))
md_path <- latest_version(file.path(ep_path_in, "metadata"))

# Stats generated by RFlux
st_path <- latest_version(file.path(wd, "processing", "00_raw_output", "stats"))

# Footprint inputs
fp_inputs <- latest_version(fp_path_in)
#fetch_input <- latest_version(fp_path_in, "fetch")

# Set tag for creating output file names
tag_out <- create_tag(settings$site, settings$year, settings$date)

# Set path for output files
path_out <- file.path(wd, "processing", "06_flux_qc")


### Load required input data ===================================================

cat("Importing data files.\n")

# Load the data
data <- readr::read_csv(
  data_input, guess_max = 6000, 
  col_types = readr::cols(.default = readr::col_guess()), progress = FALSE
)

# Load the footprint data
fp <- fp_inputs %>%
  purrr::map(~ readr::read_csv(
    .x, guess_max = 6000, 
    col_types = readr::cols(.default = readr::col_guess()), progress = FALSE
  )) %>%
  purrr::reduce(dplyr::full_join, by = "timestamp")

# Bind footprint data to main data frame
data <- dplyr::left_join(data, fp, by = "timestamp")


### Error levels ===============================================================

# Load RFlux functions
# TODO these need to be re-written and included in this script
devtools::load_all("~/Desktop/DATA/Flux/tools/RFlux", quiet = TRUE)

# Create workset for RFlux input
# - this just gathers data so doesn't need to be written to file
workset <- ecworkset(ep_path, qc_path, md_path, st_path)

# Pre-screen fluxes for periods when rain may have affected sensors
workset <- workset %>%
  # Add gap-filled rain data
  dplyr::bind_cols(dplyr::select(data, p_rain_f)) %>%
  dplyr::mutate(dplyr::across(
    c(H, LE, CO2flux, CH4flux, CO2str, CH4str),
    ~ dplyr::if_else(!is.na(p_rain_f) & p_rain_f != 0, NA_real_, .x)
  )) %>%
  dplyr::select(-p_rain_f)

# Run the quality control procedure, write to file
cleanFlux(
  workset, md_path, 
  path_output = file.path(path_out, "results"), 
  file_name = paste0("qc_results_", tag_out), 
  plot_qc = FALSE, storage = TRUE
) 

# Read in results
data_c <- readr::read_csv(
  latest_version(file.path(path_out, "results")),  
  col_types = readr::cols(.default = readr::col_guess()), 
  na = c("", "NA", "-9999"), guess_max = 6000, progress = FALSE
)

# Parse timestamp and tidy
data_c <- data_c %>%
  dplyr::mutate(
    timestamp = lubridate::ymd_hm(TIMESTAMP_END)
  ) %>%
  dplyr::select(timestamp, dplyr::everything()) %>%
  dplyr::rename_with(tolower) %>%
  dplyr::left_join(dplyr::select(data, timestamp, night), by = "timestamp")

# Recode outlying flags - SKIP
data_c <- dplyr::mutate(
  data_c,
  nee_outlying_flag = dplyr::if_else(
    nee_outlying_flag == 1 & nee_data_flag > 0, 2L, nee_outlying_flag
  ),
  nee_outlying_flag = dplyr::if_else(
    nee_outlying_flag == 1 & nee_data_flag > 0, 2L, nee_outlying_flag
  ),
  nee_outlying_flag = dplyr::if_else(
    nee_outlying_flag == 1 & nee_data_flag > 0, 2L, nee_outlying_flag
  ),
  fch4_outlying_flag = dplyr::if_else(
    fch4_outlying_flag == 1 & fch4_data_flag > 0, 2L, fch4_outlying_flag
  )
)

# Examine flags
data_c %>%
  mutate(qc = factor(nee_data_flag)) %>%
  ggplot(aes(timestamp, fc, color = qc)) +
  facet_wrap(~ night) +
  geom_point() +
  ylim(-40, 40)
data_c %>%
  mutate(qc = factor(fch4_data_flag)) %>%
  ggplot(aes(timestamp, fm, color = qc)) +
  facet_wrap(~ night) +
  geom_point() +
  ylim(-0.75, 1.25)

# Outlier detection
# - seasonal-trend decomposition based on LOESS

# Examine flags
data_c %>%
  mutate(
    ol = factor(nee_outlying_flag),
    fc = if_else(nee_data_flag == 2, NA_real_, fc), qc = factor(nee_data_flag)
  ) %>%
  ggplot(aes(timestamp, fc, color = ol, shape = qc)) +
  facet_wrap(~ night) +
  geom_point()
data_c %>%
  mutate(
    ol = factor(fch4_outlying_flag),
    fm = if_else(fch4_data_flag == 2, NA_real_, fm), qc = factor(fch4_data_flag)
  ) %>%
  ggplot(aes(timestamp, fm, color = ol, shape = qc)) +
  facet_wrap(~ night) +
  geom_point()

# Examine data without outliers
data_c %>%
  ggplot(aes(timestamp, nee)) +
  geom_point()
data_c %>%
  ggplot(aes(timestamp, fch4)) +
  geom_point()

# Other things to possibly look at:
# - excessive spectral correction factor (>3)
# - gas mixing ratio
# - sensor stability
#   - ch4 fluxes with RSSI < 10 are already removed by EddyPro
# - residual vertical wind component (>0.35)
# - t_sonic_sigma (>1) - for fc


# Flag high uncertainty (i.e. low quality) in remaining fluxes
# remove ch4 random uncertainty > 0.2? (see Runkle2019)
data_c %>% 
  mutate(qc = factor(pull(data, h_randunc_hf) > 25)) %>%
  ggplot(aes(timestamp, h, color = qc)) +
  geom_point()
data_c %>% 
  mutate(qc = factor(pull(data, le_randunc_hf) > 50)) %>%
  ggplot(aes(timestamp, le, color = qc)) +
  geom_point()
data_c %>% 
  mutate(qc = factor(pull(data, fc_randunc_hf) > 10)) %>%
  ggplot(aes(timestamp, nee, color = qc)) +
  geom_point()
data_c %>% 
  mutate(qc = factor(pull(data, fch4_randunc_hf) > 0.2)) %>%
  ggplot(aes(timestamp, fch4, color = qc)) +
  geom_point()
data_c <- data_c %>%
  mutate(
    h_rand_unc = pull(data, h_randunc_hf),
    le_rand_unc = pull(data, le_randunc_hf),
    nee_rand_unc = pull(data, fc_randunc_hf),
    fch4_rand_unc = pull(data, fch4_randunc_hf),
    
    h_unc_flag = flag_thr(h_rand_unc, 25, "higher"),
    le_unc_flag = flag_thr(le_rand_unc, 50, "higher"),
    nee_unc_flag = flag_thr(nee_rand_unc, 5, "higher"),
    fch4_unc_flag = flag_thr(fch4_rand_unc, 0.1, "higher")
  )

# Footprint coverage of AOI
data_c %>%
  mutate(nee = clean(nee, nee_unc_flag), flag = factor(foot_flag)) %>%
  left_join(fp) %>%
  ggplot(aes(timestamp, nee, color = flag)) +
  geom_point(size = 1)
data_c %>%
  mutate(nee = clean(nee, nee_unc_flag)) %>%
  left_join(fp) %>%
  ggplot(aes(timestamp, nee, color = phi_k15 > 0.80)) +
  geom_point(size = 1)
# Phi K15 looks GOOD
data_c %>%
  mutate(nee = clean(nee, nee_unc_flag)) %>%
  left_join(fp) %>%
  ggplot(aes(timestamp, nee, color = phi_km01 > 0.80)) +
  geom_point(size = 1)
data_c %>%
  mutate(fch4 = clean(fch4, fch4_unc_flag), flag = factor(foot_flag)) %>%
  left_join(fp) %>%
  ggplot(aes(timestamp, fch4, color = flag)) +
  geom_point(size = 1)
data_c %>%
  mutate(fch4 = clean(fch4, fch4_unc_flag)) %>%
  left_join(fp) %>%
  ggplot(aes(timestamp, fch4, color = phi_k15 > 0.80)) +
  geom_point(size = 1)


data_c <- data_c %>%
  mutate(
    phi = pull(fp, phi_k15),
    phi_flag = flag_thr(phi, 0.80, "lower")
  )


clean_st %>%
  mutate(timestamp = ymd_hm(TIMESTAMP_END)) %>%
  bind_cols(select(site, phi, phi_ffp, night, fc_ss, fch4_randunc_hf)) %>%
  #filter(NEE_DATA_FLAG != 2, NEE_OUTLYING_FLAG != 1) %>%
  drop_na(NEE) %>% filter(phi_ffp > 0.80) %>% 
  group_by(night) %>% 
  summarize(
    low = quantile(NEE, c(0.005, 0.995), na.rm = TRUE)[1], 
    high = quantile(NEE, c(0.005, 0.995), na.rm = TRUE)[2]
  )

