### ============================================================================
# Flux quality control =========================================================
### ============================================================================


# Purpose: 

# Input(s):

# Output(s):

# Load the required packages
devtools::load_all("~/Desktop/RESEARCH/fluxtools", quiet = TRUE)
library(openeddy)
library(lubridate)
library(tidyverse)

source("~/Desktop/DATA/Flux/tools/reference/site_metadata.R")
source("~/Desktop/DATA/Flux/tools/reference/essential_vars.R")

### Helper functions ===========================================================

flag_thr <- function(x, thr, 
                     rule = c("higher", "lower", "outside", "between")) {
  
  rule <- rlang::arg_match(rule)
  
  if (rule == "higher") {
    flag <- dplyr::if_else(x > thr, 2L, 0L)
  } else if (rule == "lower") {
    flag <- dplyr::if_else(x < thr, 2L, 0L)
  } else if (rule == "outside") {
    thr <- sort(thr)
    flag <- dplyr::if_else(x < thr[1] | x > thr[2], 2L, 0L)
  } else if (rule == "between") {
    thr <- sort(thr)
    flag <- dplyr::if_else(x > thr[1] & x < thr[2], 2L, 0L)
  }
  
  flag
}


### Initialize script settings & documentation =================================

# Load metadata file
md <- purrr::pluck(site_metadata, settings$site)

# Set the desired working directory in RStudio interface
# - assumes that the subdirectory structure is already present
wd <- file.path("~/Desktop", "DATA", "Flux", settings$site, settings$year)
path_in <- file.path(wd, "processing_data", "05_biomet_gapfill", "output")
ep_path_in <- file.path(wd, "processing_data", "02_combine_eddypro", "output")
fp_path_in <- file.path(wd, "processing_data", "06_footprint", "output")

# Input file - biomet output with QC flags
site_input <- latest_version(path_in, "biomet_gf")

# EddyPro outputs (for RFlux)
ep_path <- latest_version(ep_path_in, "full_output_combined")
qc_path <- latest_version(ep_path_in, "qc_details_combined")
md_path <- latest_version(ep_path_in, "metadata_combined")

# Stats generated by RFlux
st_path <- latest_version(
  file.path(wd, "processing_data", "08_flux_qc"), "rflux_qcstats"
)

# Footprint input
fp_input <- latest_version(fp_path_in, "footprint_basics")
ffp_input <- latest_version(fp_path_in, "footprint_basics_ffp")
fetch_input <- latest_version(fp_path_in, "fetch")

# Set tag for creating output file names
tag_out <- create_tag(settings$site, settings$year, settings$date)

# Set path for output files
path_out <- file.path(wd, "processing_data", "08_flux_qc", "output")


### Load required input data ===================================================

# EddyPro
site <- read.csv(site_input, stringsAsFactors = FALSE)

# Add timestamp components
site <- site %>% 
  dplyr::mutate(timestamp = lubridate::ymd_hms(timestamp, tz = md$tz_name)) %>%
  add_time_comps()

# Footprint
#fp <- read.csv(fp_input, stringsAsFactors = FALSE)

# Add timestamp components
#fp <- mutate(fp, timestamp = ymd_hms(timestamp, tz = md$tz_name))

# Bind footprint data to main data frame
#site <- left_join(site, fp)

# FFP
ffp <- read.csv(ffp_input, stringsAsFactors = FALSE)

# Add timestamp components
ffp <- dplyr::mutate(
  ffp, timestamp = lubridate::ymd_hms(timestamp, tz = md$tz_name)
)

# Bind ffp data to main data frame
site <- dplyr::left_join(site, ffp, by = "timestamp")

# Add 'daytime' variable based on sw_in_f
site <- dplyr::mutate(site, daytime = sw_in_f > 20)


### Error levels ===============================================================

# Load RFlux functions
rflux <- list.files("~/Desktop/DATA/Flux/tools/RFlux", full.names = TRUE)
purrr::map(rflux, source)

# Create workset for RFlux input
ws_path <- file.path(
  dirname(path_out), paste0("rflux_workset_", tag_out, ".csv")
)
workset <- ecworkset(
  ep_path, qc_path, md_path, st_path, 
  dirname(tools::file_path_sans_ext(ws_path)), 
  basename(tools::file_path_sans_ext(ws_path))
)
ws_path <- latest_version(dirname(path_out), "rflux_workset")

# Pre-screen fluxes for periods when rain may have affected sensors
workset <- workset %>%
  dplyr::bind_cols(dplyr::select(site, p_rain_f)) %>%
  dplyr::mutate(dplyr::across(
    c(H, LE, CO2flux, CH4flux, CO2str, CH4str),
    ~ dplyr::if_else(!is.na(p_rain_f) & p_rain_f != 0, NA_real_, .)
  )) %>%
  dplyr::select(-p_rain_f)

# Run the quality control procedure
clean <- cleanFlux(
  workset, md_path, path_output = NULL, FileName = NULL, 
  plotQC = FALSE, storage = TRUE
) 

clean <- clean %>%
  tibble::as_tibble() %>%
  dplyr::mutate(
    timestamp = lubridate::ymd_hm(TIMESTAMP_END, tz = md$tz_name)
  ) %>%
  dplyr::select(timestamp, dplyr::everything()) %>%
  dplyr::rename_with(tolower) %>%
  dplyr::left_join(dplyr::select(site, timestamp, daytime), by = "timestamp")

# Evidence of systematic error in raw data

# Percent fluxes removed due to severe error
#clean %>% summarize(p = 1 - (length(na.omit(nee)) / length(na.omit(fc))))
#clean %>% summarize(p = 1 - (length(na.omit(fch4)) / length(na.omit(fm))))

# Examine flags
clean %>%
  mutate(qc = factor(nee_data_flag)) %>%
  ggplot(aes(timestamp, fc, color = qc)) +
  facet_wrap(~ daytime) +
  geom_point() +
  ylim(-40, 40)
clean %>%
  mutate(qc = factor(fch4_data_flag)) %>%
  ggplot(aes(timestamp, fm, color = qc)) +
  facet_wrap(~ daytime) +
  geom_point() +
  ylim(-0.75, 1.25)

# Outlier detection
# - seasonal-trend decomposition based on LOESS

# Percent fluxes identified as outliers
clean %>% 
  filter(!is.na(nee_outlying_flag)) %>% 
  summarize(p = 1 - (n() - sum(nee_outlying_flag)) / n())
clean %>% 
  filter(!is.na(fch4_outlying_flag)) %>% 
  summarize(p = 1 - (n() - sum(fch4_outlying_flag)) / n())

# Examine flags
clean %>%
  mutate(
    ol = factor(nee_outlying_flag),
    fc = if_else(nee_data_flag == 2, NA_real_, fc), qc = factor(nee_data_flag)
  ) %>%
  ggplot(aes(timestamp, fc, color = ol, shape = qc)) +
  facet_wrap(~ daytime) +
  geom_point()
clean %>%
  mutate(
    ol = factor(fch4_outlying_flag),
    fm = if_else(fch4_data_flag == 2, NA_real_, fm), qc = factor(fch4_data_flag)
  ) %>%
  ggplot(aes(timestamp, fm, color = ol, shape = qc)) +
  facet_wrap(~ daytime) +
  geom_point()

# Examine data without outliers
clean %>%
  ggplot(aes(timestamp, nee)) +
  geom_point()
clean %>%
  ggplot(aes(timestamp, fch4)) +
  geom_point()

# Overall percent of fluxes remaining
#clean %>% summarize(p = 1 - (length(na.omit(nee)) / length(na.omit(fc))))
#clean %>% summarize(p = 1 - (length(na.omit(fch4)) / length(na.omit(fm))))

# Other things to possibly look at:
# - excessive spectral correction factor (>3)
# - gas mixing ratio
# - sensor stability
#   - ch4 fluxes with RSSI < 10 are already removed by EddyPro
# - residual vertical wind component (>0.35)


# Flag high uncertainty (i.e. low quality) in remaining fluxes
# remove ch4 random uncertainty > 0.2? (see Runkle2019)
clean %>% 
  mutate(qc = factor(pull(site, h_randunc_hf) > 25)) %>%
  ggplot(aes(timestamp, h, color = qc)) +
  geom_point()
clean %>% 
  mutate(qc = factor(pull(site, le_randunc_hf) > 50)) %>%
  ggplot(aes(timestamp, le, color = qc)) +
  geom_point()
clean %>% 
  mutate(qc = factor(pull(site, fc_randunc_hf) > 5)) %>%
  ggplot(aes(timestamp, nee, color = qc)) +
  geom_point()
clean %>% 
  mutate(qc = factor(pull(site, fch4_randunc_hf) > 0.1)) %>%
  ggplot(aes(timestamp, fch4, color = qc)) +
  geom_point()
clean <- clean %>%
  mutate(
    h_rand_unc = pull(site, h_randunc_hf),
    le_rand_unc = pull(site, le_randunc_hf),
    nee_rand_unc = pull(site, fc_randunc_hf),
    fch4_rand_unc = pull(site, fch4_randunc_hf),
    
    h_unc_flag = flag_thr(h_rand_unc, 25),
    le_unc_flag = flag_thr(le_rand_unc, 50),
    nee_unc_flag = flag_thr(nee_rand_unc, 5),
    fch4_unc_flag = flag_thr(fch4_rand_unc, 0.1)
  )

# Footprint coverage of AOI
clean %>%
  mutate(nee = clean(nee, nee_unc_flag), flag = factor(foot_flag)) %>%
  left_join(ffp) %>%
  ggplot(aes(timestamp, nee, color = flag)) +
  geom_point(size = 1)
clean %>%
  mutate(nee = clean(nee, nee_unc_flag)) %>%
  left_join(ffp) %>%
  ggplot(aes(timestamp, nee, color = phi_ffp > 0.80)) +
  geom_point(size = 1)
clean %>%
  mutate(fch4 = clean(fch4, fch4_unc_flag), flag = factor(foot_flag)) %>%
  left_join(ffp) %>%
  ggplot(aes(timestamp, fch4, color = flag)) +
  geom_point(size = 1)
clean %>%
  mutate(fch4 = clean(fch4, fch4_unc_flag)) %>%
  left_join(ffp) %>%
  ggplot(aes(timestamp, fch4, color = phi_ffp > 0.80)) +
  geom_point(size = 1)


clean <- clean %>%
  mutate(
    phi = pull(ffp, phi_ffp),
    phi_flag = flag_thr(phi, 0.80, "lower")
  )

#site %>% bind_cols(fch4_qc) %>% filter(qc_fch4_max != 2) %>% plot_dygraph(fch4)

clean_st %>%
  mutate(timestamp = ymd_hm(TIMESTAMP_END)) %>%
  bind_cols(select(site, phi, phi_ffp, night, fc_ss, fch4_randunc_hf)) %>%
  #filter(NEE_DATA_FLAG != 2, NEE_OUTLYING_FLAG != 1) %>%
  drop_na(NEE) %>% filter(phi_ffp > 0.80) %>% 
  group_by(night) %>% 
  summarize(
    low = quantile(NEE, c(0.005, 0.995), na.rm = TRUE)[1], 
    high = quantile(NEE, c(0.005, 0.995), na.rm = TRUE)[2]
  )


### Visual precheck ============================================================

# Display variables that can help identify problems with instruments
names <- c(
  "u_rot", "v_rot", "w_unrot", "w_rot", "sonic_temperature", "max_wind_speed",
  "tau", "ustar", "h", "le", "fc", "fch4",
  "u_var", "v_var", "w_var", "ts_var", "h2o_var", "co2_var", "ch4_var",
  "rand_err_tau", "rand_err_h", "rand_err_le", "rand_err_fc", "rand_err_fch4",
  "tau_scf", "h_scf", "le_scf", "co2_scf", "ch4_scf",
  "u_spikes", "v_spikes", "w_spikes", "ts_spikes", "co2_spikes", "ch4_spikes",
  "h2o_v_adv", "co2_v_adv", "ch4_v_adv",
  "co2_mixing_ratio", "h2o_mixing_ratio", "ch4_mixing_ratio", 
  "co2_time_lag", "h2o_time_lag", "ch4_time_lag",
  "x_peak_h00", "x_90perc_h00"
)


# Bind qc flags to main data frame
full <- left_join(site, site_qc)

# Save dataset
full_out <- paste0(
  wd, "/08_flux_qc/output/", "flux_qc_full_", tag_out, ".csv"
)
write.csv(full, full_out, row.names = FALSE)

# Gather & save essentials dataset
essentials <- site %>%
  dplyr::select(!!essentials) %>%
  dplyr::left_join(select_at(site_qc, vars(timestamp, ends_with("final"))))

essentials_out <- paste0(
  wd, "/08_flux_qc/output/", "flux_qc_essentials_", tag_out, ".csv"
)
write.csv(essentials, essentials_out, row.names = FALSE)



### Quality checking - preliminary flags =======================================


# Get a subsetted data frame with all recognizable QC information
site_qc <- site %>%
  select_at(vars(
    ends_with("_ssitc_test"), 
    ends_with("_ss_test"), 
    ends_with("_vm97_test"), # 800011199 
    # - spikes, ampres, dropout, abslim, skw/kur, discont, timelag, angle, steady
    ends_with("_itc"), ends_with("_ss"), # Foken stats used to calculate flags
    ends_with("_nsr"), # Mahrt 1998 Nonstationarity Ratios
    ends_with("_corrdiff"), # Correlation differences with/without repeat values
    ends_with("_zcd"), # Zero-Counts on Differenced variables
    ends_with("_kid"), # Kurtosis Index on Differenced variables
    ends_with("_hf")
  ))







### Quality checking - other indicators of sensor problems/flux issues =========

# Test out any custom flags outside the standard set
# - e.g. precip lags, probable condensation, skewness/kurtosis, etc.

# Look at how sensors respond after precip events
# - vars to check: fc, co2_mixing_ratio, co2_var, inst_li7500_agc_or_rssi
# - tau, w_unrot, w_var, sonic_temperature (-1, 1), ts_var (0, 4)
site %>%
  mutate(var = clean(inst_li7500_agc_or_rssi, qc_fc_std)) %>%
  spread_lags("var", 24, 48, keep_vars = c("p_rain")) %>%
  filter(p_rain > 0) %>%
  mutate(event_id = dplyr::row_number()) %>%
  gather("n_after", "var", -p_rain, -event_id) %>%
  mutate(n_after = as.numeric(n_after)) %>%
  filter(!is.na(var)) %>%
  ggplot(aes(n_after, var)) +
  stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1))

# Flux
site %>%
  mutate(fc = clean(fc, qc_fc_std)) %>%
  spread_lags("fc", 24, 48, keep_vars = c("p_rain")) %>%
  filter(p_rain > 0) %>%
  mutate(event_id = dplyr::row_number()) %>%
  gather("n_after", "fc", -p_rain, -event_id) %>%
  mutate(n_after = as.numeric(n_after)) %>%
  filter(!is.na(fc)) %>%
  group_by(n_after) %>%
  summarize(mean = mean(fc), sd = sd(fc))
# - erratic behavior from -1 to 9
# Gas concentration
site %>%
  mutate(co2 = clean(co2_mixing_ratio, qc_fc_std)) %>%
  spread_lags("co2", 24, 48, keep_vars = c("p_rain")) %>%
  filter(p_rain > 0) %>%
  mutate(event_id = dplyr::row_number()) %>%
  gather("n_after", "co2", -p_rain, -event_id) %>%
  mutate(n_after = as.numeric(n_after)) %>%
  filter(!is.na(co2)) %>%
  group_by(n_after) %>%
  summarize(mean = mean(co2), sd = sd(co2))
# - erratic behavior from -1 to 1
# Gas concentration variance
site %>%
  mutate(co2_var = clean(co2_meas_sigma, qc_fc_std)) %>%
  spread_lags("co2_var", 24, 48, keep_vars = c("p_rain")) %>%
  filter(p_rain > 0) %>%
  mutate(event_id = dplyr::row_number()) %>%
  gather("n_after", "co2_var", -p_rain, -event_id) %>%
  mutate(n_after = as.numeric(n_after)) %>%
  filter(!is.na(co2_var)) %>%
  group_by(n_after) %>%
  summarize(mean = mean(co2_var), sd = sd(co2_var))
# - erratic behavior from -2 to 3
# Sensor signal strength
site %>%
  mutate(rssi = clean(co2_signal_strength_7500_mean, qc_fc_std)) %>%
  spread_lags("rssi", 24, 48, keep_vars = c("p_rain")) %>%
  filter(p_rain > 0) %>%
  mutate(event_id = dplyr::row_number()) %>%
  gather("n_after", "rssi", -p_rain, -event_id) %>%
  mutate(n_after = as.numeric(n_after)) %>%
  filter(!is.na(rssi)) %>%
  group_by(n_after) %>%
  summarize(mean = mean(rssi), sd = sd(rssi))
# - erratic behavior from -2 to 6




### QC Summary =================================================================

# NOTE: this is messy, but it does what I need it to do
# - should clean it up at some point though 
# - need to consider how best to bundle different pieces & retain flexibility

# Create final combined flags
# Add key of combined flags to reference list
combn_flags <- append(combn_flags, list(
  qc_tau_final = c("qc_tau_prelim"),
  qc_h_final = c("qc_h_comp", "qc_h_spikesLF", "qc_all_fetch70"),
  qc_le_final = c("qc_le_comp", "qc_le_spikesLF", "qc_all_fetch70"),
  qc_fc_final = c(
    "qc_fc_comp", "qc_fc_spikesLF", "qc_all_fetch70", "qc_fc_ustar"
  )
))
combn_flags # check the list

# Create the combined final flags
QC <- QC %>%
  mutate(
    qc_tau_final = combn_QC(., combn_flags$qc_tau_final, "qc_tau_final"),
    qc_h_final = combn_QC(., combn_flags$qc_h_final, "qc_h_final"),
    qc_le_final = combn_QC(., combn_flags$qc_le_final, "qc_le_final"),
    qc_fc_final = combn_QC(., combn_flags$qc_fc_final, "qc_fc_final")
  )

# Preview final flags
# h
site %>%
  left_join(QC) %>%
  mutate(
    clean = clean(h, qc_h_final),
    flag = factor(qc_h_final)
  ) %>%
  select(timestamp, orig = h, clean, flag) %>%
  gather("type", "h", -timestamp, -flag) %>%
  filter(!is.na(h)) %>%
  ggplot(aes(timestamp, h, color = flag)) +
  facet_wrap(~type, scales = "free") +
  geom_point(alpha = 0.5)
# le
site %>%
  left_join(QC) %>%
  mutate(
    clean = clean(le, qc_le_final),
    flag = factor(qc_le_final)
  ) %>%
  select(timestamp, orig = le, clean, flag) %>%
  gather("type", "le", -timestamp, -flag) %>%
  filter(!is.na(le)) %>%
  ggplot(aes(timestamp, le, color = flag)) +
  facet_wrap(~type, scales = "free") +
  geom_point(alpha = 0.5)
# fc
site %>%
  left_join(QC) %>%
  mutate(
    clean = clean(fc, qc_fc_final),
    flag = factor(qc_fc_final)
  ) %>%
  select(timestamp, orig = fc, clean, flag) %>%
  gather("type", "fc", -timestamp, -flag) %>%
  filter(!is.na(fc)) %>%
  ggplot(aes(timestamp, fc, color = flag)) +
  facet_wrap(~type, scales = "free") +
  geom_point(alpha = 0.5)

# Summarize results of QC flagging
QC %>%
  left_join(select(site, timestamp, tau, h, le, fc, sw_in_f)) %>%
  # Recode interdep flags to account for additivity
  mutate(
    qc_h_interdep = if_else(qc_h_comp == 2 & qc_h_prelim != 2, 2L, 0L),
    qc_le_interdep = if_else(qc_le_comp == 2 & qc_le_prelim != 2, 2L, 0L),
    qc_fc_interdep = if_else(qc_fc_comp == 2 & qc_fc_prelim != 2, 2L, 0L)
  ) %>%
  # Get vector of all flagged observations
  gather("flag", "value", -timestamp, -tau, -h, -le, -fc, -sw_in_f) %>%
  # Remove unflagged observations
  mutate(value = if_else(value > 1, 1, 0)) %>%
  #filter(value == 1) %>%
  group_by(timestamp) %>%
  # Add the number of flags applied for each flux at each timestamp
  mutate(
    tau_flags = sum(
      flag %in% expand_list(combn_flags, "qc_tau_final") & value == 1, 
      na.rm = TRUE
    ),
    h_flags = sum(
      flag %in% expand_list(combn_flags, "qc_h_final") & value == 1, 
      na.rm = TRUE
    ),
    le_flags = sum(
      flag %in% expand_list(combn_flags, "qc_le_final") & value == 1, 
      na.rm = TRUE
    ),
    fc_flags = sum(
      flag %in% expand_list(combn_flags, "qc_fc_final") & value == 1,
      na.rm = TRUE
    )
  ) %>%
  group_by(flag) %>%
  summarize(
    # Number of observations flagged by each test
    n = sum(value, na.rm = TRUE),
    n_tau = sum(value[!is.na(tau)], na.rm = TRUE),
    n_h = sum(value[!is.na(h)], na.rm = TRUE),
    n_le = sum(value[!is.na(le)], na.rm = TRUE),
    n_fc = sum(value[!is.na(fc)], na.rm = TRUE),
    n_fc_day = sum(value[!is.na(fc) & sw_in_f > 20], na.rm = TRUE),
    n_fc_night = sum(value[!is.na(fc) & sw_in_f < 20], na.rm = TRUE),
    # Percent of observations flagged by each test
    p_tau = n_tau / sum(!is.na(tau)),
    p_h = n_h / sum(!is.na(h)),
    p_le = n_le / sum(!is.na(le)),
    p_fc = n_fc / sum(!is.na(fc)),
    p_fc_day = n_fc_day / sum(!is.na(fc[sw_in_f > 20])),
    p_fc_night = n_fc_night / sum(!is.na(fc[sw_in_f < 20])),
    # Number of observations *uniquely* flagged by each test
    n_distinct_tau = sum(tau_flags == 1 & !is.na(tau)),
    n_distinct_h = sum(h_flags == 1 & !is.na(h)),
    n_distinct_le = sum(le_flags == 1 & !is.na(le)),
    n_distinct_fc = sum(fc_flags == 1 & !is.na(fc))
  ) %>%
  # Round proportions to two decimal places
  mutate_if(is.numeric, round, 2) %>%
  # Remove values for flags that do not apply to flux
  mutate_at(
    vars(contains("tau")), ~ifelse(str_detect(flag, combn_flags$tau), ., NA)
  ) %>%
  mutate_at(
    vars(contains("h")), ~ifelse(str_detect(flag, combn_flags$h), ., NA)
  ) %>%
  mutate_at(
    vars(contains("le")), ~ifelse(str_detect(flag, combn_flags$le), ., NA)
  ) %>%
  mutate_at(
    vars(contains("fc")), ~ifelse(str_detect(flag, combn_flags$fc), ., NA)
  )


# Next get number of observations uniquely flagged by each test
# - how to iterate this across other flux vars?
flag_stats <- site %>%
  # Remove missing flux values
  filter(!is.na(fc)) %>%
  select(timestamp) %>%
  # Attach QC flags for each observation
  left_join(select_at(QC, vars(timestamp, combn_flags$qc_fc_std))) %>%
  # Get vector of all flagged observations
  gather("flag", "value", -timestamp) %>%
  filter(value > 1) %>%
  select(-value) %>%
  # Remove observations that are flagged by multiple tests
  group_by(timestamp) %>%
  filter(n() == 1) %>%
  # Group by the flag name, summarize number of uniquely flagged observations
  group_by(flag) %>%
  summarize(unique = n_distinct(timestamp))


### QC for Ch4 flux data =======================================================


# ch4_tlag_actual, ch4_tlag_used, ch4_tlag_nominal, ch4_tlag_min, ch4_tlag_max
# ch4_meas_skw, ch4_meas_kur, w_skw, w_kur











